"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowDown, ArrowRight, Building2, CalendarDays, Check, ChevronRight, Droplets, Hammer, Home, Mail, MapPin, Menu, PackageOpen, Phone, Sparkles, SprayCan, Users, X } from "lucide-react";

const phone="919003177051";
const services=[
  {icon:Droplets,title:"Carpet shampooing",text:"Deep extraction care that lifts embedded dirt, stains and odours from carpets."},
  {icon:Home,title:"House deep cleaning",text:"A detailed, top-to-bottom reset for apartments, villas, move-ins and move-outs."},
  {icon:Building2,title:"Office & commercial cleaning",text:"Reliable cleaning programmes shaped around your working hours and property."},
  {icon:SprayCan,title:"Pest control",text:"Targeted pest-control support for homes, offices and commercial premises."},
  {icon:Sparkles,title:"Marble polishing",text:"Professional restoration that returns clarity and shine to marble floors."},
  {icon:Hammer,title:"Mosaic polishing",text:"Mechanical finishing for a brighter, smoother and better-presented surface."},
  {icon:PackageOpen,title:"Equipment & materials",text:"Cleaning equipment, consumables and housekeeping raw materials from one source."},
  {icon:Users,title:"Manpower supply",text:"Housekeeping and facility staff matched to your operational needs."},
];
const industries=["Homes & apartments","Corporate offices","Hotels & restaurants","Retail spaces","Healthcare facilities","Educational institutions","Warehouses & commercial properties"];
const wa=(message:string)=>`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;

export default function Page(){
 const [menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[intro,setIntro]=useState(true),[progress,setProgress]=useState(0);
 useEffect(()=>{
  const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const timer=window.setTimeout(()=>setIntro(false),reduced?100:2800);
  const fn=()=>{setScrolled(window.scrollY>40);setProgress((window.scrollY/(document.documentElement.scrollHeight-window.innerHeight))*100)};
  fn();window.addEventListener("scroll",fn,{passive:true});
  const sections=document.querySelectorAll("main > section, main > footer"); sections.forEach(s=>s.classList.add("ad-section"));
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("in-frame")}),{threshold:.14,rootMargin:"0px 0px -8% 0px"});sections.forEach(s=>observer.observe(s));
  return()=>{window.clearTimeout(timer);window.removeEventListener("scroll",fn);observer.disconnect()}
 },[]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const msg=["Hello Dust To Shine, I would like a free quote.",`Name: ${d.get("name")}`,`Phone: ${d.get("phone")}`,`Email: ${d.get("email")||"-"}`,`Property: ${d.get("property")}`,`Service: ${d.get("service")}`,`Location: ${d.get("location")}`,`Preferred date: ${d.get("date")||"Flexible"}`,`Message: ${d.get("message")||"-"}`].join("\n");window.open(wa(msg),"_blank","noopener,noreferrer")}
 return <main id="top" className={intro?"intro-active":"intro-complete"}>
  <div className={`brand-film ${intro?"playing":"finished"}`} aria-hidden={!intro}><div className="film-grain"/><div className="logo-stage"><div className="logo-rings"><i/><i/><i/></div><img src="/dts-logo.jpg" alt="Dust To Shine Facility Management Services"/><p>Every space deserves its shine.</p><span className="loader-line"><b/></span></div></div>
  <div className="scroll-progress" aria-hidden="true"><span style={{width:`${progress}%`}}/></div>
  <header className={`site-header ${scrolled?"is-scrolled":""}`}><a className="brand" href="#top" aria-label="Dust To Shine home"><img src="/dts-logo.jpg" alt="Dust To Shine Facility Management Services"/></a><nav className={menu?"nav-open":""} aria-label="Main navigation"><a href="#services" onClick={()=>setMenu(false)}>Services</a><a href="#industries" onClick={()=>setMenu(false)}>Industries</a><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#plans" onClick={()=>setMenu(false)}>AMC plans</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a><a className="header-cta" href="#contact">Get a quote <ArrowRight size={16}/></a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header>
  <section className="hero" aria-labelledby="hero-title"><img className="hero-image" src="/hero-transform.webp" alt="A luxury interior transforming from dull and dusty to polished and luminous" fetchPriority="high"/><div className="hero-shade"/><div className="dust" aria-hidden="true">{[...Array(16)].map((_,i)=><i key={i}/>)}</div><div className="hero-content"><p className="kicker"><span/> Chennai · Residential · Commercial</p><h1 id="hero-title">From dust to shine.<br/><em>We transform every space.</em></h1><p>Professional cleaning, polishing, pest control, manpower and complete facility-management solutions for homes and businesses.</p><div className="hero-actions"><a className="btn btn-cyan" href="#contact">Get a free quote <ArrowRight/></a><a className="btn btn-glass" href={wa("Hello Dust To Shine, I would like to discuss a service.")} target="_blank" rel="noreferrer">Chat on WhatsApp</a></div></div><div className="hero-meta"><span>Serving Chennai</span><span>One-time & AMC</span><span>Homes & businesses</span></div><a className="scroll-cue" href="#trust"><ArrowDown/><span>Discover</span></a></section>
  <section className="trust" id="trust" aria-label="Service commitments"><div><Users/><span>Trained workforce</span></div><div><Sparkles/><span>Professional equipment</span></div><div><Building2/><span>Residential & commercial</span></div><div><CalendarDays/><span>One-time & AMC options</span></div></section>
  <section className="section services" id="services"><div className="section-intro"><p className="kicker"><span/> What we do</p><h2>Specialist care.<br/><em>One accountable team.</em></h2><p>From a single deep-cleaning requirement to recurring facility support, every engagement is shaped around your property and schedule.</p></div><div className="service-track">{services.map((s,i)=>{const Icon=s.icon;return <article className="service-card" key={s.title}><span className="card-no">0{i+1}</span><Icon/><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Request this service <ChevronRight/></a></article>})}</div></section>
  <section className="feature" id="about"><div className="feature-media"><img src="/facility-team.webp" alt="Professional facility-management team working in a premium office lobby" loading="lazy"/><span>Complete facility management</span></div><div className="feature-copy"><p className="kicker"><span/> One partner, complete care</p><h2>Your facilities,<br/><em>professionally managed.</em></h2><p>Dust To Shine combines cleaning, manpower, supplies, maintenance coordination and AMC support into one clear, dependable service relationship.</p><ul><li><Check/>A service plan tailored to your property</li><li><Check/>Residential and commercial coverage</li><li><Check/>One-time and recurring support</li><li><Check/>Multiple facility needs through one provider</li></ul><a className="text-link" href="#contact">Plan your facility support <ArrowRight/></a></div></section>
  <section className="section process"><div className="section-intro compact"><p className="kicker"><span/> Simple by design</p><h2>From requirement to <em>remarkable.</em></h2></div><div className="steps">{[["01","Share your requirement","Tell us about the property and service you need."],["02","Consultation","We understand the site, scope and right approach."],["03","Customised quote","Receive a clear proposal shaped around your needs."],["04","Execute & check","Our team completes the work and reviews quality."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="polish-story"><img src="/marble-polish.webp" alt="Professional floor-polishing equipment restoring a marble surface" loading="lazy"/><div><p className="kicker"><span/> Precision in every pass</p><h2>Dull surfaces.<br/><em>Brilliant finishes.</em></h2><p>Specialist marble and mosaic polishing brings back clarity, depth and a premium finish—without making promises the surface cannot support.</p><a className="btn btn-light" href="#contact">Ask about floor polishing <ArrowRight/></a></div></section>
  <section className="section industries" id="industries"><div className="section-intro"><p className="kicker"><span/> Industries served</p><h2>Built around the way<br/><em>your space works.</em></h2><p>Flexible facility solutions for everyday living, customer-facing businesses and operational environments.</p></div><div className="industry-grid">{industries.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3><ArrowRight/></div>)}</div></section>
  <section className="plans" id="plans"><div className="plans-head"><p className="kicker"><span/> Service continuity</p><h2>Choose the rhythm<br/><em>that fits your space.</em></h2></div>{[["01","One-time service","For deep cleaning, urgent pest treatment, floor restoration or a specific facility requirement.","Request a quote"],["02","Scheduled maintenance","Planned visits that keep your property consistently clean, presentable and cared for.","Plan a schedule"],["03","Customised AMC","A recurring agreement combining the services, staffing and frequency your operation requires.","Discuss an AMC"]].map((x,i)=><div className={`plan-card ${i===1?"featured":""}`} key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><a href="#contact">{x[3]} <ArrowRight/></a></div>)}</section>
  <section className="section contact" id="contact"><div className="contact-copy"><p className="kicker"><span/> Start a conversation</p><h2>Ready to transform<br/><em>your space?</em></h2><p>Share your requirement and continue securely on WhatsApp. We will connect with you to understand the scope and prepare the next step.</p><div className="contact-list"><a href="tel:+919003177051"><Phone/><span><small>Call us</small>+91 90031 77051</span></a><a href="mailto:dusttoshinefacility@gmail.com"><Mail/><span><small>Email</small>dusttoshinefacility@gmail.com</span></a><div><MapPin/><span><small>Address</small>29/10, Bharathidasan Street, Kumaran Colony 2nd Street, Saidapet, Chennai – 600015</span></div></div></div><form onSubmit={submit} className="quote-form"><div className="form-row"><label>Name<input name="name" required autoComplete="name"/></label><label>Phone number<input name="phone" required type="tel" autoComplete="tel"/></label></div><div className="form-row"><label>Email<input name="email" type="email" autoComplete="email"/></label><label>Property type<select name="property" required defaultValue=""><option value="" disabled>Select</option><option>Residential</option><option>Commercial</option></select></label></div><label>Required service<select name="service" required defaultValue=""><option value="" disabled>Select a service</option>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Complete facility management</option></select></label><div className="form-row"><label>Property / location<input name="location" required/></label><label>Preferred date<input name="date" type="date"/></label></div><label>Message<textarea name="message" rows={3}/></label><label className="consent"><input name="consent" type="checkbox" required/> I agree to be contacted about this enquiry.</label><button className="btn btn-cyan" type="submit">Continue on WhatsApp <ArrowRight/></button></form></section>
  <footer><div className="footer-main"><img src="/dts-logo.jpg" alt="Dust To Shine"/><p>Professional facility care for homes, offices and commercial spaces across Chennai.</p><div><strong>Explore</strong><a href="#services">Services</a><a href="#industries">Industries</a><a href="#plans">AMC plans</a></div><div><strong>Contact</strong><a href="tel:+919003177051">+91 90031 77051</a><a href="mailto:dusttoshinefacility@gmail.com">Email us</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Dust To Shine Facility Management Services</span><span><a href="/privacy">Privacy policy</a><a href="/terms">Terms & conditions</a></span></div></footer>
  <a className="float-wa" href={wa("Hello Dust To Shine, I need a service quote.")} target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp">WA</a><div className="mobile-actions"><a href="tel:+919003177051"><Phone/> Call</a><a href={wa("Hello Dust To Shine, I need a service quote.")} target="_blank" rel="noreferrer">WhatsApp</a></div>
 </main>
}
